// eslint-disable-next-line import/no-anonymous-default-export
export default {
    name: "Ali Nayebi",
    home: "HOME",
    about: "ABOUT",
    resume: "RESUME",
    portfolios: "PORTFOLIOS",
    contact: "CONTACT",
    hi: "Hi, I am ",
    hi2: "",
    desc: "I am a frontend web developer. I can provide clean code and pixle perfect design. I also make wesite more & more interactive with web animations.",
    aboutme: "ABOUT ME",
    services: "SERVICES",
    fullname: "Full Name",
    age: "Age",
    nationality: "Nationality",
    languages: "Languages",
    phone: "Phone",
    years: "24 Years",
    iranian: "Iranian",
    farsi: "Farsi",
    english: "English",
    phonenumber: "(+98)9216057609",
    downloadcv: "download cv",
    webdesign: "Web Design",
    webdevelopment: "Web Development",
    mobileapplication: "Mobile Application",
    servicedesc: "Lorem ipsum dolor sit amet consectetur ratione quod.",
    myskills: "MY SKILLS",
    workingSteps: [
        {
            id: -1,
            date: "",
            title: "",
            subtitle: "",
            content: "",
        },
        {
            id: 0,
            date: "2018-2019",
            title: "Frontend Web Developer",
            subtitle: "Abc University",
            content: "asfA SF  asf ASFD a sf SF  sdfhfg aljkhdfal khga sdlkfhg alksdjfhga sdfkljas dflkjh asdfkjhsa df;khg asd;kjgas dk;jhgdsa d;kgh asd;kgjh sad;fkj ds fksadfh sadufh sadlkf hsadf lksduh fsdaLorem ipsum dolor sit amet consectetur ratione quod.",
        },
        {
            id: 1,
            date: "2018-2019",
            title: "Backend Web Developer",
            subtitle: "Abc University",
            content: "asfA SF asf ASFD a sf SF sdfhfg aljkhdfal khga sdlkfhg alksdjfhga sdfkljas dflkjh asdfkjhsa df;khg asd;kjgas dk;jhgdsa d;kgh asd;kgjh sad;fkj ds fksadfh sadufh sadlkf hsadf lksduh fsdaLorem ipsum dolor sit amet consectetur ratione quod.",
        },
        {
            id: -2,
            date: "",
            title: "",
            subtitle: "",
            content: "",
        },
    ],
    educationalSteps: [
        {
            id: -1,
            date: "",
            title: "",
            subtitle: "",
            content: "",
        },
        {
            id: 0,
            date: "2018-2019",
            title: "Master of Science",
            subtitle: "Abc University",
            content: "asfA SF  asf ASFD a sf SF  sdfhfg aljkhdfal khga sdlkfhg alksdjfhga sdfkljas dflkjh asdfkjhsa df;khg asd;kjgas dk;jhgdsa d;kgh asd;kgjh sad;fkj ds fksadfh sadufh sadlkf hsadf lksduh fsdaLorem ipsum dolor sit amet consectetur ratione quod.",
        },
        {
            id: 1,
            date: "2018-2019",
            title: "Bachelor of Science",
            subtitle: "Abc University",
            content: "asfA SF asf ASFD a sf SF sdfhfg aljkhdfal khga sdlkfhg alksdjfhga sdfkljas dflkjh asdfkjhsa df;khg asd;kjgas dk;jhgdsa d;kgh asd;kgjh sad;fkj ds fksadfh sadufh sadlkf hsadf lksduh fsdaLorem ipsum dolor sit amet consectetur ratione quod.",
        },
        {
            id: 2,
            date: "2018-2019",
            title: "High School Graduation",
            subtitle: "Abc University",
            content: "asfA SF asf ASFD a sf SF sdfhfg aljkhdfal khga sdlkfhg alksdjfhga sdfkljas dflkjh asdfkjhsa df;khg asd;kjgas dk;jhgdsa d;kgh asd;kgjh sad;fkj ds fksadfh sadufh sadlkf hsadf lksduh fsdaLorem ipsum dolor sit amet consectetur ratione quod.",
        },
        {
            id: -2,
            date: "",
            title: "",
            subtitle: "",
            content: "",
        },
    ],
    workingexperience: "Working Experience",
    educationalqualifications: "Educational Qualifications",
    contactme: "CONTACT ME",
    getintouch: "Get In Touch",
    enteryourname: "Enter your name",
    enteryouremail: "Enter your email",
    enteryoursubject: "Enter your subject",
    enteryourmessage: "Enter your message",
    sendmessage: "Send Message",
    email: "Email",
    address: "Address",
    addressdetail: "121 King Street, Melbourne, Victoria 3000, Austrailia",
    phone1: "+012-3456-7891",
    phone2: "+012-3456-7891",
    portfolioslist: [
        { id: 1, title: "reactdeveloper", desc: "react js teacher reactdeveloper.ir", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
        { id: 2, title: "reactnativedeveloper", desc: "reactnative teacher reactnativedeveloper.ir", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
        { id: 3, title: "reactdeveloper", desc: "react js teacher", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
        { id: 4, title: "reactdeveloper", desc: "react js teacher", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
        { id: 5, title: "reactdeveloper", desc: "react js teacher", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
        { id: 6, title: "reactdeveloper", desc: "react js teacher", image: "https://img.freepik.com/premium-photo/image-colorful-galaxy-sky-generative-ai_791316-9864.jpg?w=2000", },
    ],
}